# Generated by Django 3.0.3 on 2020-02-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indId', models.CharField(max_length=20)),
                ('indTname', models.CharField(max_length=20)),
                ('indExp', models.CharField(max_length=20)),
                ('indCost', models.CharField(max_length=20)),
                ('indSite', models.CharField(max_length=20)),
                ('indRole', models.CharField(max_length=20)),
                ('indTenure', models.CharField(max_length=20)),
                ('indOnoroff', models.CharField(max_length=20)),
                ('indThxNotesG', models.CharField(max_length=20)),
                ('indThxNotesR', models.CharField(max_length=20)),
                ('indGrade', models.CharField(max_length=20)),
                ('indNoPto', models.CharField(max_length=20)),
                ('indDoj', models.CharField(max_length=20)),
                ('indSkillLevel', models.CharField(max_length=20)),
                ('indSkill', models.CharField(max_length=20)),
            ],
        ),
    ]
