# Generated by Django 3.0.3 on 2020-02-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuals',
            name='indTenure',
        ),
        migrations.AlterField(
            model_name='individuals',
            name='indDoj',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='individuals',
            name='indId',
            field=models.IntegerField(),
        ),
    ]
