# Generated by Django 3.0.3 on 2020-02-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadfile', '0002_auto_20200219_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prjnumbers',
            fields=[
                ('prjID', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(default='prj', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TempTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('indId', models.IntegerField()),
                ('tdevopsRatio', models.IntegerField()),
                ('tdesignRatio', models.IntegerField()),
                ('tavgTenure', models.IntegerField()),
                ('tOnOffRatio', models.IntegerField()),
                ('tratioGtAvgExp', models.IntegerField()),
                ('tpctThxNotesG', models.IntegerField()),
                ('tpctThxNotesR', models.IntegerField()),
                ('tAvgDurationBygrade', models.IntegerField()),
                ('tpctGdurationGtAvgduration', models.IntegerField()),
                ('tAvgNoOfPto', models.IntegerField()),
                ('tPctPepleGtAvgpto', models.IntegerField()),
                ('tPctSameJdate', models.IntegerField()),
                ('tFitnessValue', models.IntegerField()),
            ],
        ),
    ]
