# Generated by Django 3.0.3 on 2020-02-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadfile', '0003_prjnumbers_tempteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempteam',
            old_name='tAvgDurationBygrade',
            new_name='tAvgSkillLevel',
        ),
        migrations.RenameField(
            model_name='tempteam',
            old_name='tPctPepleGtAvgpto',
            new_name='tCntdistinctskills',
        ),
        migrations.RenameField(
            model_name='tempteam',
            old_name='tPctSameJdate',
            new_name='tavgCost',
        ),
        migrations.RemoveField(
            model_name='tempteam',
            name='tavgTenure',
        ),
        migrations.RemoveField(
            model_name='tempteam',
            name='tpctGdurationGtAvgduration',
        ),
        migrations.RemoveField(
            model_name='tempteam',
            name='tpctThxNotesG',
        ),
        migrations.RemoveField(
            model_name='tempteam',
            name='tpctThxNotesR',
        ),
        migrations.AlterField(
            model_name='tempteam',
            name='tFitnessValue',
            field=models.CharField(max_length=20),
        ),
    ]
