# Generated by Django 3.0.3 on 2020-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadfile', '0004_auto_20200221_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndConsidered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indId', models.IntegerField()),
            ],
        ),
    ]
